"""Initial dynamic schema

Revision ID: 4b13e2d1013f
Revises: 
Create Date: 2025-12-06 12:50:59.460987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4b13e2d1013f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dynamic_test_session',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('spec_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('target_base_url', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='sessionstatus'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('initiated_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dynamic_finding',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('session_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('endpoint_path', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('check_type', sa.Enum('BOLA', 'BROKEN_AUTH', 'DATA_EXPOSURE', 'OTHER', name='checktype'), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='severity'), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['dynamic_test_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dynamic_test_case',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('session_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('endpoint_path', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('check_type', sa.Enum('BOLA', 'BROKEN_AUTH', 'DATA_EXPOSURE', 'OTHER', name='checktype'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'EXECUTED', 'SKIPPED', name='casestatus'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['dynamic_test_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dynamic_evidence',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('finding_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('request_dump', sa.Text(), nullable=True),
    sa.Column('response_dump', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['dynamic_finding.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finding_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dynamic_evidence')
    op.drop_table('dynamic_test_case')
    op.drop_table('dynamic_finding')
    op.drop_table('dynamic_test_session')
    # ### end Alembic commands ###
