"""Add spec_json to StaticSpec

Revision ID: 5af2645ff1f7
Revises: 2fab52643c85
Create Date: 2025-12-06 17:57:50.761883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5af2645ff1f7'
down_revision: Union[str, None] = '2fab52643c85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('static_spec', sa.Column('spec_json', mysql.LONGTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('static_spec', 'spec_json')
    # ### end Alembic commands ###
