"""Add StaticSpec table

Revision ID: ecc64d2baf15
Revises: 4b13e2d1013f
Create Date: 2025-12-06 12:52:48.614890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ecc64d2baf15'
down_revision: Union[str, None] = '4b13e2d1013f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('static_spec',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('blueprint_json', sa.Text(), nullable=True),
    sa.Column('scan_details_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'dynamic_test_session', 'static_spec', ['spec_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dynamic_test_session', type_='foreignkey')
    op.drop_table('static_spec')
    # ### end Alembic commands ###
